<?php

namespace Database\Seeders;

use App\Models\Budget;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BudgetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Alat/Bahan untuk Kegiatan Kantor Benda Pos',
                'uraian' => 'Materai',
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '45',
                'satuan' => 'Orang/kegiatan',
                'harga_satuan' => 10000.00,
                'jumlah_anggaran' => 450000,
                'bobot' => 0.53,
                'volume_nominal_rr' => 45.00,
                'satuan_rr' => 'Orang/kegiatan',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 0.51,
                'volume_nominal_rf' => 45.00,
                'satuan_rf' => 'Orang/kegiatan',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 0.51,
                'rupiah_rk' => 450000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 0.51,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Makanan dan Minuman Rapat',
                'uraian' => 'Pengadaan Makanan dan Minuman Jamuan/Uang Makan/Kudapan (Snack) Acara di Kantor Spesifikasi: Kudapan (Snack)',
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '150',
                'satuan' => 'Orang/kegiatan',
                'harga_satuan' => 15000.00,
                'jumlah_anggaran' => 2250000,
                'bobot' => 2.66,
                'volume_nominal_rr' => 150.00,
                'satuan_rr' => 'Orang/kegiatan',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 2.72,
                'volume_nominal_rf' => 150.00,
                'satuan_rf' => 'Orang/kegiatan',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 2.72,
                'rupiah_rk' => 2400000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 2.72,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Kawat/Faksimili/Internet/TV Berlangganan',
                'uraian' => "Office 365\nSpesifikasi: Microsoft Office 365 Original",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '4',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 200000.00,
                'jumlah_anggaran' => 800000,
                'bobot' => 0.95,
                'volume_nominal_rr' => 0.07,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 0.07,
                'volume_nominal_rf' => 4.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 0.07,
                'rupiah_rk' => 8000000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 0.07,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Kawat/Faksimili/Internet/TV Berlangganan',
                'uraian' => "Windows\nSpesifikasi: Microsoft Windows 11 Profesional 32bit/64bit",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '12',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 3500000.00,
                'jumlah_anggaran' => 42000000,
                'bobot' => 49.64,
                'volume_nominal_rr' => 12.00,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 47.62,
                'volume_nominal_rf' => 12.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 47.62,
                'rupiah_rk' => 42000000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 47.62,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Pemeliharaan Komputer-Peralatan Komputer-Peralatan Mainframe',
                'uraian' => "Pemeliharaan Dana Perbaikan Alat Pendukung Utama (APU)\nSpesifikasi: Pemeliharaan dan Perbaikan Alat Pendukung Utama (APU)",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '1',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 15000000.00,
                'jumlah_anggaran' => 15000000,
                'bobot' => 17.73,
                'volume_nominal_rr' => 1.00,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 17.01,
                'volume_nominal_rf' => 1.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 17.01,
                'rupiah_rk' => 15000000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 17.01,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Perjalanan Dinas Biasa',
                'uraian' => "Biaya Taksi Perjalanan Dinas Dalam Negeri\nSpesifikasi: D.K.I Jakarta",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '6',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 256000.00,
                'jumlah_anggaran' => 1536000,
                'bobot' => 1.82,
                'volume_nominal_rr' => 6.00,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 1.74,
                'volume_nominal_rf' => 6.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 1.74,
                'rupiah_rk' => 1536000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 1.74,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Perjalanan Dinas Biasa',
                'uraian' => "Biaya Taksi Perjalanan Dinas Dalam Negeri \nSpesifikasi: Riau",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '6',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 730000.00,
                'jumlah_anggaran' => 4380000,
                'bobot' => 5.18,
                'volume_nominal_rr' => 6.00,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 4.97,
                'volume_nominal_rf' => 6.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 4.97,
                'rupiah_rk' => 4380000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 4.97,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Perjalanan Dinas Biasa',
                'uraian' => "Penginapan Perjalanan Dinas Luar Daerah (Pejabat Eselon IIV/JFU & JFT Golongan IV)\nSpesifikasi: D.K.I Jakarta",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '6',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 730000.00,
                'jumlah_anggaran' => 4380000,
                'bobot' => 5.18,
                'volume_nominal_rr' => 4.97,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 4.97,
                'volume_nominal_rf' => 6.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 4.97,
                'rupiah_rk' => 4380000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 4.97,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Perjalanan Dinas Biasa',
                'uraian' => "Uang Harian Perjalanan Dinas Luar Daerah\nSpesifikasi: D.K.I Jakarta",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '9',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 530000.00,
                'jumlah_anggaran' => 4770000,
                'bobot' => 5.64,
                'volume_nominal_rr' => 9.00,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 5.41,
                'volume_nominal_rf' => 9.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 5.41,
                'rupiah_rk' => 4770000.00,
                'persentase_rk' => 100.00,
                'tertimbang_rk' => 5.41,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal_anggaran' => Carbon::now(),
                'judul' => 'Penyediaan Layanan Keamanan Informasi Pemerintah Daerah Provinsi',
                'sub_judul' => 'Operasional Jaring Komunikasi Sandi Daerah Provinsi Riau',
                'sub_sub_judul' => 'Belanja Perjalanan Dinas Biasa',
                'uraian' => "Uang Transportasi Udara (PP) - Ekonomi\nSpesifikasi: D.K.I Jakarta",
                'pejabat_penanggung_jawab' => null,
                'waktu_pelaksanaan' => null,
                'volume' => '3',
                'satuan' => 'Orang/kali',
                'harga_satuan' => 3016000.00,
                'jumlah_anggaran' => 9048000,
                'bobot' => 10.69,
                'volume_nominal_rr' => 3.00,
                'satuan_rr' => 'Orang/kali',
                'fisik_rr' => 100.00,
                'tertimbang_rr' => 10.26,
                'volume_nominal_rf' => 3.00,
                'satuan_rf' => 'Orang/kali',
                'fisik_rf' => 100.00,
                'tertimbang_rf' => 10.26,
                'rupiah_rk' => 9048000.00,
                'persentase_rk' => 99.47,
                'tertimbang_rk' => 10.26,
                'sisa_anggaran' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($data as $item) {
            Budget::create($item);
        }
    }
}
